In [7]:
graph = [
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
]

In [8]:
def is_simple_graph(graph):
    n_vertices = len(graph)
    for i in range(n_vertices):
        if graph[i][i] == 1: # has_self_loop
            return False
    return True

is_simple_graph(graph)

True

In [9]:
def is_undirected_graph(graph):
    n_vertices = len(graph)
    for i in range(n_vertices):
        for j in range(n_vertices):
            if graph[i][j] != graph[i][j]:
                return False
    return True

is_undirected_graph(graph)

True

In [10]:
def is_connected_graph_dfs(graph, start_vertex):
    n_vertices = len(graph)
    visited = [False]*n_vertices
    n_visited = 1
    s = [start_vertex]
    visited[start_vertex] = True
    visit_sequence = [start_vertex]
    while len(s) > 0:
        current_vertex = s.pop()
        for i in range(n_vertices):
            if visited[i] == True:
                continue
            else:
                if graph[current_vertex][i] == 1:
                    visited[i] = True
                    s.append(i)
                    n_visited += 1
                    visit_sequence.append(i)
    print(visit_sequence)
    if n_visited < n_vertices:
        return False
    return True

is_connected_graph_dfs(graph, 0)

[0, 1, 3, 5, 7, 8, 4, 9, 6, 2]


True

In [11]:
import numpy as np

def matrix_power(A, power):
        result = np.eye(len(A), dtype=int)
        for _ in range(power):
            result = np.dot(result, A)
        return result

def min_l_no_zero_entry(graph):
    A = np.array(graph)
    n = len(A)
    
    for l in range(1, n**2 + 1):
        A_l = matrix_power(A, l)
        print(f'l={l} : A_l={A_l}')
        if np.all(A_l > 0):
            return l
    
    return -1

min_l_no_zero_entry(graph)

l=1 : A_l=[[0 1 0 1 0 1 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 1 1 0]
 [0 1 0 0 0 0 0 0 1 1]
 [1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 1]
 [0 0 0 0 1 0 1 0 1 0]]
l=2 : A_l=[[3 1 1 2 1 1 0 1 1 0]
 [1 4 0 1 0 2 0 1 2 1]
 [1 0 1 1 1 0 0 0 0 0]
 [2 1 1 5 2 1 0 0 0 1]
 [1 0 1 2 3 0 1 0 1 1]
 [1 2 0 1 0 2 0 1 1 0]
 [0 0 0 0 1 0 1 0 1 0]
 [1 1 0 0 0 1 0 1 1 0]
 [1 2 0 0 1 1 1 1 3 1]
 [0 1 0 1 1 0 0 0 1 3]]
l=3 : A_l=[[ 4  7  1  7  2  5  0  2  3  2]
 [ 7  2  4 10  7  2  1  1  2  2]
 [ 1  4  0  1  0  2  0  1  2  1]
 [ 7 10  1  4  2  7  1  5  8  2]
 [ 2  7  0  2  2  3  1  2  6  5]
 [ 5  2  2  7  3  2  0  1  1  1]
 [ 0  1  0  1  1  0  0  0  1  3]
 [ 2  1  1  5  2  1  0  0  0  1]
 [ 3  2  2  8  6  1  1  0  2  5]
 [ 2  2  1  2  5  1  3  1  5  2]]
l=4 : A_l=[[19 14  7 21 12 11  2  7 11  5]
 [14 28  2 14  6 17  2 10 19 10]
 [ 7  2  4 10  7  2  1  1  2  2]
 [21 14 10 37 20 11  2  4  8 11]
 [12  6  7 20 18  4  5  2  9  9]
 [

4

In [12]:
def count_connected_components(graph):
    def dfs(vertex, visited):
        stack = [vertex]
        while stack:
            v = stack.pop()
            if not visited[v]:
                visited[v] = True
                for i, is_connected in enumerate(graph[v]):
                    if is_connected and not visited[i]:
                        stack.append(i)

    num_vertices = len(graph)
    visited = [False] * num_vertices
    connected_components = 0

    for v in range(num_vertices):
        if not visited[v]:
            dfs(v, visited)
            connected_components += 1

    return connected_components

print(count_connected_components(graph))  # Output: Number of connected components


1


In [13]:
def node_degrees(graph):
    num_vertices = len(graph)
    degrees = [0] * num_vertices

    for i in range(num_vertices):
        for j in range(num_vertices):
            if graph[i][j] == 1:
                degrees[i] += 1

    min_degree = min(degrees)
    max_degree = max(degrees)

    return degrees, min_degree, max_degree

node_degrees(graph)

([3, 4, 1, 5, 3, 2, 1, 1, 3, 3], 1, 5)

In [14]:
matrix_power(graph, 5)

array([[46, 59, 14, 62, 30, 40,  5, 21, 38, 25],
       [59, 36, 28, 88, 57, 28, 10, 14, 30, 27],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [62, 88, 14, 58, 33, 58, 11, 37, 68, 30],
       [30, 57,  6, 33, 24, 32,  9, 20, 47, 32],
       [40, 28, 17, 58, 32, 22,  4, 11, 19, 16],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [38, 30, 19, 68, 47, 19,  9,  8, 26, 33],
       [25, 27, 10, 30, 32, 16, 13, 11, 33, 20]])

# Small graph

In [21]:
def read_graph_from_file(filename):
    graph = {}
    n_edges = 0
    with open(filename, 'r') as file:
        for line in file:
            n_edges += 1
            u, v = map(int, line.strip().split())
            if u not in graph:
                graph[u] = []
            graph[u].append(v)
    print(f'n_edges={n_edges}')
    return graph

graph = read_graph_from_file('release_directed_graph.txt')

n_edges=1030


In [22]:
graph

{0: [3, 10, 12, 25, 39, 50, 74, 76, 84, 87, 89, 96],
 1: [4, 10, 13, 25, 29, 31, 33, 35, 74, 82],
 2: [3, 4, 31, 38, 42, 44, 49, 66, 73, 75, 93],
 3: [4, 12, 17, 24, 30, 31, 33, 53, 71, 94],
 4: [3, 21, 24, 37, 46, 58, 60, 79, 81, 93, 97],
 5: [6, 35, 89, 96],
 6: [30, 33, 35, 50, 62, 80],
 7: [35, 41, 51, 71, 74, 77, 79, 81, 88, 94],
 8: [1, 34, 59, 61, 63, 66, 67, 82],
 9: [10, 21, 27, 29, 38, 45, 48, 52, 61, 65, 84, 86, 93],
 10: [7, 21, 52, 61, 83, 99],
 11: [1, 19, 25, 36, 42, 52, 54, 56, 59, 77, 83, 84, 90, 94, 98],
 12: [2, 10, 27, 28, 37, 42, 65, 80, 90, 94, 98],
 13: [3, 21, 26, 35, 39, 40, 50, 53, 66, 74, 77, 81, 84, 97],
 14: [0, 20, 28, 48, 52, 55, 57, 70, 78, 88, 91, 92, 95],
 15: [8, 11, 12, 29, 34, 41, 71, 89, 90],
 16: [18, 21, 36, 74, 83, 92],
 17: [1, 5, 8, 10, 18, 28, 29, 32, 33, 45, 52, 55, 57, 60, 65, 80, 87, 88, 98],
 18: [5, 6, 16, 23, 25, 32, 44, 58, 86, 93, 96],
 19: [8, 10, 19, 31, 39, 50, 53, 74, 81, 84, 85, 94],
 20: [11, 29, 34, 49, 63, 71, 79, 83, 89, 98, 

In [23]:
len(graph.keys())

100

In [24]:
def convert_to_adjacency_matrix(graph):
    n_vertices = len(graph.keys())
    adjacency_graph = [[0 for _ in range(n_vertices)] for _ in range(n_vertices)]
    for k, v in graph.items():
        for i in v:
            adjacency_graph[k][i] = 1
    return adjacency_graph

graph = convert_to_adjacency_matrix(graph)

In [25]:
is_simple_graph(graph)

False

## Check if a directed graph contains cycles

To check if a directed graph contains cycles (excluding self-loops), we can use Depth-First Search (DFS). One effective algorithm for this purpose is Tarjan's algorithm, which finds strongly connected components (SCCs) in a graph. If any SCC contains more than one node, it means the graph contains a cycle.

In [26]:
def has_directed_cycle(graph):
    n = len(graph)
    index = 0
    stack = []
    indices = [-1] * n
    lowlink = [-1] * n
    on_stack = [False] * n
    result = []

    def strongconnect(v):
        nonlocal index
        indices[v] = index
        lowlink[v] = index
        index += 1
        stack.append(v)
        on_stack[v] = True

        for w in range(n):
            if graph[v][w]:
                if indices[w] == -1:
                    strongconnect(w)
                    lowlink[v] = min(lowlink[v], lowlink[w])
                elif on_stack[w]:
                    lowlink[v] = min(lowlink[v], indices[w])

        if lowlink[v] == indices[v]:
            scc = []
            while True:
                w = stack.pop()
                on_stack[w] = False
                scc.append(w)
                if w == v:
                    break
            if len(scc) > 1:
                result.append(scc)

    for v in range(n):
        if indices[v] == -1:
            strongconnect(v)

    return len(result) > 0

has_directed_cycle(graph)


True
